import { useState } from 'react';
import { Alert, Modal, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View, type DimensionValue } from 'react-native';
import { getCompletedCount, getCompletionRate } from '../domain/habits';
import { useHabits } from '../context/habits-context';

const C={ink:'#10120F',paper:'#F4F2EA',card:'#FFF',lime:'#D9FF43',muted:'#6E726B',line:'#D7D9D1',danger:'#A83A2D'};
export function Loading(){return <View style={s.loading}><Text style={s.logo}>R</Text><Text style={s.caption}>RHYTHMを準備しています</Text></View>}
export function Header({kicker,title,meta}:{kicker:string;title:string;meta?:string}){return <View style={s.header}><View><Text style={s.eyebrow}>{kicker}</Text><Text style={s.title}>{title}</Text></View>{meta?<Text style={s.meta}>{meta}</Text>:<View style={s.avatar}><Text style={s.bold}>K</Text></View>}</View>}
function Primary({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.primary,disabled&&s.disabled,pressed&&s.pressed]}><Text style={s.primaryText}>{label}</Text></Pressable>}

export function HomeScreen(){
  const {state,ready,toggle,remove,add}=useHabits();const [open,setOpen]=useState(false);const [title,setTitle]=useState('');
  if(!ready)return <Loading/>;const completed=getCompletedCount(state.habits),rate=getCompletionRate(state.habits);
  const submit=()=>{if(!title.trim())return;add(title);setTitle('');setOpen(false)};
  return <View style={s.page}><ScrollView style={s.screen} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <Header kicker="GOOD MORNING" title="今日の習慣" meta={completed+'/'+state.habits.length}/>
    <View style={s.track} accessibilityLabel={'今日の達成率 '+rate+'パーセント'}><View style={[s.fill,{width:(rate+'%') as DimensionValue}]}/></View>
    <View style={s.row}><Text style={s.section}>TODAY</Text><Text style={s.caption}>{rate}% 完了</Text></View>
    <View style={s.list}>{state.habits.map(h=><Pressable key={h.id} accessibilityRole="checkbox" accessibilityState={{checked:h.completed}} accessibilityHint="タップで切替、長押しで削除" onPress={()=>toggle(h.id)}
      onLongPress={()=>Alert.alert('習慣を削除しますか？','この操作は元に戻せません。',[{text:'キャンセル',style:'cancel'},{text:'削除',style:'destructive',onPress:()=>remove(h.id)}])}
      style={({pressed})=>[s.habit,h.completed&&s.habitDone,pressed&&s.pressed]}><View style={[s.check,h.completed&&s.checkDone]}><Text style={s.checkText}>{h.completed?'✓':''}</Text></View>
      <View style={{flex:1}}><Text style={[s.cardTitle,state.largeText&&s.cardTitleLarge,h.completed&&s.done]}>{h.title}</Text><Text style={s.caption}>{h.completed?'今日も達成しました':'タップで完了'}</Text></View><Text style={s.streak}>{h.streak}日</Text></Pressable>)}</View>
    {state.habits.length===0&&<View style={s.empty}><Text style={s.cardTitle}>最初の習慣を追加しましょう</Text><Text style={s.body}>小さく続けられる内容がおすすめです。</Text></View>}
    <Primary label="＋ 習慣を追加" onPress={()=>setOpen(true)}/><Text style={s.helper}>習慣を長押しすると削除できます</Text>
  </ScrollView><Modal transparent visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><Pressable style={{flex:1}} onPress={()=>setOpen(false)} accessibilityLabel="閉じる"/>
    <View style={s.sheet}><View style={s.handle}/><Text style={s.eyebrow}>NEW HABIT</Text><Text style={s.sheetTitle}>続けたい習慣を追加</Text><TextInput autoFocus value={title} onChangeText={setTitle} onSubmitEditing={submit} returnKeyType="done" maxLength={30} accessibilityLabel="習慣名" placeholder="例：15分読書する" placeholderTextColor="#888" style={s.input}/><Text style={s.count}>{title.length}/30</Text><Primary label="追加する" onPress={submit} disabled={!title.trim()}/><Pressable onPress={()=>setOpen(false)} style={s.cancel}><Text style={s.caption}>キャンセル</Text></Pressable></View>
  </View></Modal></View>
}

export function ProgressScreen(){
  const {state,ready}=useHabits();if(!ready)return <Loading/>;const completed=getCompletedCount(state.habits),rate=getCompletionRate(state.habits),week=[42,68,54,86,rate,28,12],days=['月','火','水','木','金','土','日'];
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><Header kicker="THIS WEEK" title="進捗レポート"/><View style={s.scoreCard}><Text style={s.light}>今日の達成率</Text><Text style={s.score}>{rate}<Text style={s.percent}>%</Text></Text><Text style={s.light}>{completed} / {state.habits.length}件の習慣を完了</Text></View>
    <View style={s.chartCard}><View style={s.row}><Text style={s.section}>7 DAYS</Text><Text style={s.caption}>週間の記録</Text></View><View style={s.chart} accessibilityLabel="7日間の達成率グラフ">{week.map((v,i)=><View key={days[i]} style={s.column}><View style={s.barTrack}><View style={[s.bar,{height:(Math.max(v,8)+'%') as DimensionValue}]}/></View><Text style={s.caption}>{days[i]}</Text></View>)}</View></View>
    <View style={s.insight}><Text style={s.spark}>✦</Text><View style={{flex:1}}><Text style={s.cardTitle}>{rate>=75?'良いペースです':'小さく続けましょう'}</Text><Text style={s.body}>{rate>=75?'今日の目標まであと少しです。':'1つ完了するだけでも前進です。'}</Text></View></View></ScrollView>
}

export function SettingsScreen(){
  const {state,ready,setLargeText,setReminder,reset}=useHabits();if(!ready)return <Loading/>;
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><Header kicker="PREFERENCES" title="設定"/><View style={s.settings}>
    <Setting label="大きな文字" note="習慣名を読みやすくします" value={state.largeText} set={setLargeText}/><Setting label="リマインド" note={state.reminderEnabled?'毎日 20:00（デモ設定）':'オフ'} value={state.reminderEnabled} set={setReminder}/></View>
    <View style={s.note}><Text style={s.section}>DATA</Text><Text style={s.body}>習慣と設定は端末内に保存され、アプリを閉じても保持されます。</Text></View>
    <Pressable onPress={()=>Alert.alert('データをリセットしますか？','追加した習慣と設定を初期状態に戻します。',[{text:'キャンセル',style:'cancel'},{text:'リセット',style:'destructive',onPress:()=>void reset()}])} style={s.danger}><Text style={s.dangerText}>保存データをリセット</Text></Pressable><Text style={s.version}>RHYTHM 1.0.0 / SELF-INITIATED PROJECT</Text></ScrollView>
}
function Setting({label,note,value,set}:{label:string;note:string;value:boolean;set:(v:boolean)=>void}){return <View style={s.setting}><View style={{flex:1}}><Text style={s.cardTitle}>{label}</Text><Text style={s.caption}>{note}</Text></View><Switch accessibilityLabel={label} value={value} onValueChange={set} trackColor={{false:C.line,true:C.ink}} thumbColor={value?C.lime:'#fff'}/></View>}

export const tabColors={active:C.lime,inactive:'#777B73',background:C.card,border:C.line,ink:C.ink};
const s=StyleSheet.create({
  page:{flex:1},screen:{flex:1,backgroundColor:C.paper},content:{paddingHorizontal:20,paddingTop:14,paddingBottom:32},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:C.paper,gap:12},logo:{width:56,height:56,paddingTop:11,textAlign:'center',overflow:'hidden',borderRadius:18,backgroundColor:C.lime,fontSize:28,fontWeight:'900'},
  header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingBottom:28},eyebrow:{color:C.muted,fontSize:12,fontWeight:'800',letterSpacing:1.8,marginBottom:6},title:{color:C.ink,fontSize:32,lineHeight:39,fontWeight:'900',letterSpacing:-1.2},meta:{minWidth:64,padding:12,borderRadius:18,overflow:'hidden',backgroundColor:C.ink,color:C.lime,fontWeight:'900',textAlign:'center'},avatar:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:C.lime,borderWidth:1},bold:{fontWeight:'900'},
  track:{height:9,borderRadius:20,backgroundColor:C.line,overflow:'hidden',marginBottom:26},fill:{height:'100%',backgroundColor:C.ink},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},section:{fontSize:12,fontWeight:'900',letterSpacing:1.5},caption:{color:C.muted,fontSize:12,lineHeight:17},list:{gap:10},habit:{minHeight:78,flexDirection:'row',alignItems:'center',gap:14,padding:16,borderRadius:22,backgroundColor:C.card,borderWidth:1,borderColor:C.line},habitDone:{backgroundColor:'#F0FFD0',borderColor:C.ink},check:{width:42,height:42,borderRadius:15,alignItems:'center',justifyContent:'center',borderWidth:2},checkDone:{backgroundColor:C.ink},checkText:{color:C.lime,fontSize:22,fontWeight:'900'},cardTitle:{fontSize:16,lineHeight:22,fontWeight:'800',color:C.ink},cardTitleLarge:{fontSize:20,lineHeight:27},done:{textDecorationLine:'line-through',color:'#4F544C'},streak:{fontSize:12,fontWeight:'900'},body:{color:C.muted,fontSize:15,lineHeight:23},empty:{alignItems:'center',gap:6,padding:28,borderRadius:22,backgroundColor:C.card,borderWidth:1,borderColor:C.line},
  primary:{minHeight:54,marginTop:18,alignItems:'center',justifyContent:'center',borderRadius:18,backgroundColor:C.lime,borderWidth:1},primaryText:{fontSize:16,fontWeight:'900'},disabled:{opacity:.35},helper:{color:C.muted,fontSize:12,textAlign:'center',marginTop:12},scoreCard:{padding:24,borderRadius:26,backgroundColor:C.ink,marginBottom:14},light:{color:'#C8CCC3',fontSize:14},score:{color:C.lime,fontSize:72,lineHeight:82,fontWeight:'900',letterSpacing:-4},percent:{fontSize:30},chartCard:{padding:20,borderRadius:24,backgroundColor:C.card,borderWidth:1,borderColor:C.line},chart:{height:190,flexDirection:'row',justifyContent:'space-between',paddingTop:12},column:{width:'11%',height:'100%',alignItems:'center',gap:8},barTrack:{flex:1,width:'100%',justifyContent:'flex-end',overflow:'hidden',borderRadius:8,backgroundColor:'#ECEDE7'},bar:{width:'100%',borderRadius:8,backgroundColor:C.lime,borderWidth:1},
  insight:{flexDirection:'row',alignItems:'center',gap:14,padding:20,marginTop:14,borderRadius:22,backgroundColor:'#E6E1FF'},spark:{width:44,height:44,paddingTop:8,textAlign:'center',overflow:'hidden',borderRadius:15,color:'#fff',fontSize:22,backgroundColor:'#5D43C7'},settings:{borderRadius:24,overflow:'hidden',backgroundColor:C.card,borderWidth:1,borderColor:C.line},setting:{minHeight:86,flexDirection:'row',alignItems:'center',gap:16,padding:18,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:C.line},note:{gap:10,padding:20,marginTop:14,borderRadius:22,backgroundColor:'#E8EEF8'},danger:{minHeight:52,alignItems:'center',justifyContent:'center',marginTop:22,borderRadius:18,borderWidth:1,borderColor:C.danger},dangerText:{color:C.danger,fontSize:15,fontWeight:'800'},version:{color:C.muted,fontSize:10,letterSpacing:1,textAlign:'center',marginTop:24},
  pressed:{opacity:.68},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(16,18,15,.44)'},sheet:{paddingHorizontal:22,paddingTop:12,paddingBottom:Platform.OS==='ios'?34:22,borderTopLeftRadius:30,borderTopRightRadius:30,backgroundColor:C.paper},handle:{width:42,height:5,alignSelf:'center',borderRadius:10,backgroundColor:'#B9BCB4',marginBottom:24},sheetTitle:{fontSize:26,lineHeight:34,fontWeight:'900',letterSpacing:-.8,marginBottom:20},input:{height:58,paddingHorizontal:16,borderRadius:17,borderWidth:1.5,backgroundColor:C.card,fontSize:16},count:{color:C.muted,fontSize:11,textAlign:'right',marginTop:6},cancel:{minHeight:46,alignItems:'center',justifyContent:'center'},
});
