"use client";

import { useMemo, useState, type CSSProperties, type FormEvent } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, Check, CheckCircle2, ChevronRight, Code2, ExternalLink, LayoutTemplate, Menu, MousePointer2, Palette, Search, Send, Sparkles, X, Zap } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";

type Industry = {
  id: string; number: string; name: string; english: string; brand: string; concept: string;
  audience: string; goal: string; primary: string; secondary: string; ink: string; surface: string;
  image?: string; hero: string; subcopy: string; cta: string; accentCopy: string;
  hpSections: string[]; lpSections: string[]; bannerCopy: string; tags: string[]; font: string; mood: string;
};

const industries: Industry[] = [
  { id: "beauty", number: "01", name: "美容", english: "BEAUTY", brand: "LUMIÈRE SKIN", concept: "静けさの中に宿る、透明感。", audience: "30〜40代／自分の肌と丁寧に向き合いたい人", goal: "初回カウンセリング予約", primary: "#D8C29D", secondary: "#8E7256", ink: "#F8F4EC", surface: "#171713", image: "/beauty-hero.webp", hero: "肌は、もっと静かに美しくなる。", subcopy: "一人ひとりの肌履歴を読み解く、完全予約制スキンケアサロン。", cta: "肌診断を予約する", accentCopy: "FIRST TRIAL ¥6,600", hpSections: ["CONCEPT", "TREATMENT", "VOICE", "SALON", "RESERVE"], lpSections: ["悩みへの共感", "3つの原因", "施術メソッド", "症例・口コミ", "限定オファー"], bannerCopy: "初回限定｜肌質改善トリートメント 40% OFF", tags: ["余白", "高級感", "信頼性"], font: "Noto Serif JP × Inter", mood: "Editorial / Quiet luxury" },
  { id: "food", number: "02", name: "飲食", english: "DINING", brand: "季ノ皿 KINOSARA", concept: "旬を一皿に、夜を記憶に。", audience: "食に関心の高い30〜50代／記念日・会食利用", goal: "ディナーコース予約", primary: "#B6403A", secondary: "#E2B66A", ink: "#FFF8E8", surface: "#25130F", image: "/food-hero.webp", hero: "今夜、旬に会いに行く。", subcopy: "産地の景色まで味わう、季節の日本料理とナチュラルワイン。", cta: "席を予約する", accentCopy: "AUTUMN COURSE 7皿 ¥8,800", hpSections: ["旬の献立", "料理人", "空間", "お知らせ", "ご予約"], lpSections: ["季節の物語", "コース紹介", "生産者", "お客様の声", "空席案内"], bannerCopy: "秋の実りを味わう｜限定ペアリングコース", tags: ["食欲喚起", "季節感", "予約導線"], font: "Shippori Mincho × Manrope", mood: "Warm / Gastronomy" },
  { id: "fashion", number: "03", name: "アパレル", english: "FASHION", brand: "ÉLAN STUDIO", concept: "輪郭を着る。意思を纏う。", audience: "20〜30代／モードとストリートを横断する層", goal: "新作コレクション購入", primary: "#D9FF43", secondary: "#214BFF", ink: "#0B0B0B", surface: "#F6F5EF", image: "/fashion-hero.webp", hero: "WEAR YOUR POINT.", subcopy: "曖昧な毎日に、鮮明なシルエットを。SPRING / SUMMER 2026", cta: "COLLECTIONを見る", accentCopy: "DROP 02 — NOW ONLINE", hpSections: ["NEW DROP", "COLLECTION", "LOOKBOOK", "JOURNAL", "STORE"], lpSections: ["キービジュアル", "NEW ITEMS", "スタイリング", "サイズガイド", "購入CTA"], bannerCopy: "NEW DROP 02｜送料無料 9.20まで", tags: ["大胆な文字", "非対称", "スピード感"], font: "Archivo Black × Noto Sans JP", mood: "Neo editorial / Street" },
  { id: "energy", number: "04", name: "電気会社", english: "ENERGY", brand: "HIKARI ENERGY", concept: "電気を、選べる未来へ。", audience: "ファミリー世帯／電気代と環境負荷を見直したい人", goal: "料金シミュレーション完了", primary: "#62E6C7", secondary: "#3D6CFF", ink: "#F4FAFF", surface: "#071B35", hero: "使うほど、未来が明るくなる電気。", subcopy: "再生可能エネルギー比率70%。暮らしに合わせて選べるシンプルな料金プラン。", cta: "電気代を30秒で診断", accentCopy: "平均 年間12,400円 おトク", hpSections: ["料金プラン", "再エネ", "導入事例", "サポート", "会社情報"], lpSections: ["料金課題", "節約シミュレーション", "選ばれる理由", "切替手順", "申込み"], bannerCopy: "切替0円｜基本料金3か月無料キャンペーン", tags: ["安心", "明瞭", "未来感"], font: "Zen Kaku Gothic New × Inter", mood: "Clean tech / Trust" },
  { id: "campaign", number: "05", name: "キャンペーン", english: "CAMPAIGN", brand: "TOKYO CREATIVE WEEK", concept: "つくる人と、動き出す7日間。", audience: "クリエイター・学生・新しい表現に出会いたい人", goal: "無料参加登録", primary: "#FF4D00", secondary: "#6C37FF", ink: "#141414", surface: "#FFF200", hero: "IDEAS NEED A CITY.", subcopy: "展示、トーク、ワークショップ。東京の47会場をつなぐクリエイティブフェス。", cta: "無料パスを手に入れる", accentCopy: "10.12 SUN — 10.18 SAT", hpSections: ["PROGRAM", "SPEAKERS", "VENUES", "NEWS", "TICKETS"], lpSections: ["開催宣言", "注目プログラム", "登壇者", "会場MAP", "参加登録"], bannerCopy: "7 DAYS / 47 VENUES / 120 CREATORS", tags: ["話題性", "高コントラスト", "SNS拡散"], font: "Space Grotesk × Noto Sans JP", mood: "Brutal pop / Festival" },
];

const techs = [["HTML", "セマンティックな見出し構造と構造化データ"], ["CSS", "業種別トークン・レスポンシブ・アニメーション"], ["JavaScript", "タブ切替・CTA計測・メニュー制御"], ["Tailwind CSS", "素早く再利用できるUI設計"], ["TypeScript", "デザインデータとUI状態を型安全に管理"]];
const codeSamples = {
  HTML: `<main>\n  <article itemscope itemtype="https://schema.org/LocalBusiness">\n    <h1>ブランドの約束を一文で伝える</h1>\n    <a href="#reserve">予約する</a>\n  </article>\n</main>`,
  CSS: `:root {\n  --brand: #d9ff43;\n  --space-section: clamp(5rem, 10vw, 10rem);\n}\n.hero {\n  display: grid;\n  grid-template-columns: 1.1fr .9fr;\n}`,
  JavaScript: `document.querySelectorAll('[data-cta]').forEach((button) => {\n  button.addEventListener('click', () => {\n    window.dataLayer?.push({ event: 'cta_click' });\n  });\n});`,
  "Tailwind CSS": `<section className="grid min-h-[80vh] items-end\n  bg-zinc-950 px-6 py-16 text-white md:grid-cols-2 md:px-12">\n  <h1 className="text-6xl font-black tracking-[-.06em] md:text-8xl">\n    WEAR YOUR POINT.\n  </h1>\n</section>`,
  TypeScript: `type Industry = {\n  id: string;\n  goal: '予約' | '購入' | '申込';\n  palette: readonly [string, string];\n};\n\nconst trackCTA = (item: Industry) =>\n  analytics.track('conversion', { industry: item.id });`,
};

function MiniNav({ item }: { item: Industry }) { return <div className="mini-nav"><strong>{item.brand}</strong><span>{item.hpSections.slice(0, 3).join("　")}</span><Menu size={16} /></div>; }
function HeroVisual({ item, compact = false }: { item: Industry; compact?: boolean }) {
  if (item.image) return <div className={`hero-image ${compact ? "compact" : ""}`}><Image src={item.image} alt={`${item.name}業界の${item.brand}キービジュアル`} width={1536} height={1024} sizes="(max-width: 700px) 100vw, 45vw" unoptimized /></div>;
  return <div className={`generated-visual ${item.id} ${compact ? "compact" : ""}`} aria-label={`${item.name}の抽象ビジュアル`}><span className="visual-orbit" /><span className="visual-grid" /><Zap className="visual-icon" aria-hidden="true" /></div>;
}
function WebsitePreview({ item }: { item: Industry }) { return <div className="browser-frame preview-hp"><div className="browser-top"><i /><i /><i /><span>{item.brand.toLowerCase().replaceAll(" ", "-")}.jp</span></div><MiniNav item={item} /><div className="mini-hero"><div className="mini-copy"><small>{item.accentCopy}</small><h4>{item.hero}</h4><p>{item.subcopy}</p><button>{item.cta} <ArrowDownRight size={13} /></button></div><HeroVisual item={item} compact /></div><div className="mini-proof">{item.hpSections.slice(1, 4).map((section, index) => <div key={section}><b>0{index + 1}</b><span>{section}</span><em /></div>)}</div></div>; }
function LandingPreview({ item }: { item: Industry }) { return <div className="phone-frame preview-lp"><div className="phone-status"><span>9:41</span><i /></div><div className="lp-head"><b>{item.brand}</b><Menu size={14} /></div><HeroVisual item={item} compact /><div className="lp-copy"><small>{item.accentCopy}</small><h4>{item.hero}</h4><button>{item.cta}</button></div><div className="lp-flow">{item.lpSections.slice(0, 4).map((section, index) => <div key={section}><i>0{index + 1}</i><span>{section}</span></div>)}</div></div>; }
function BannerPreview({ item }: { item: Industry }) { return <div className={`banner-preview ${item.id}`}><div className="banner-copy"><small>{item.brand}</small><h4>{item.bannerCopy}</h4><span>{item.cta} <ChevronRight size={13} /></span></div><HeroVisual item={item} compact /><b className="banner-mark">{item.number}</b></div>; }
function Wireframe({ title, blocks }: { title: string; blocks: string[] }) { return <div className="wire-card"><div className="wire-head"><span>{title}</span><LayoutTemplate size={16} /></div><div className="wire-body">{blocks.map((block, index) => <div className={`wire-block wire-${index}`} key={block}><span>{block}</span><i /><i /></div>)}</div></div>; }

export default function Home() {
  const [activeId, setActiveId] = useState("beauty"); const [menuOpen, setMenuOpen] = useState(false); const [codeTab, setCodeTab] = useState<keyof typeof codeSamples>("HTML"); const [submitted, setSubmitted] = useState(false); const [submitting, setSubmitting] = useState(false); const [formError, setFormError] = useState("");
  const active = useMemo(() => industries.find((item) => item.id === activeId) ?? industries[0], [activeId]);
  const theme = { "--case-primary": active.primary, "--case-secondary": active.secondary, "--case-ink": active.ink, "--case-surface": active.surface } as CSSProperties;
  const selectIndustry = (id: string) => { setActiveId(id); document.getElementById("case-study")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const handleInquiry = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSubmitting(true); setFormError("");
    const form = event.currentTarget; const data = Object.fromEntries(new FormData(form).entries());
    try { const response = await fetch("/api/inquiries", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(data) }); const result = await response.json() as { error?:string }; if (!response.ok) throw new Error(result.error || "送信できませんでした"); setSubmitted(true); form.reset(); document.getElementById("contact")?.scrollIntoView({ behavior:"smooth", block:"center" }); }
    catch (error) { setFormError(error instanceof Error ? error.message : "送信できませんでした"); }
    finally { setSubmitting(false); }
  };
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="ページ上部へ"><span>K</span> KENTA CREATIVE</a><nav className={menuOpen ? "nav-open" : ""} aria-label="メインナビゲーション"><a href="#works" onClick={() => setMenuOpen(false)}>WORKS</a><a href="#process" onClick={() => setMenuOpen(false)}>PROCESS</a><a href="#code" onClick={() => setMenuOpen(false)}>CODE</a><Link href="/services" onClick={() => setMenuOpen(false)}>SERVICE</Link><Link href="/booking-demo" onClick={() => setMenuOpen(false)}>BOOKING DEMO</Link><a className="nav-contact" href="#contact" onClick={() => setMenuOpen(false)}>CONTACT</a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="メニューを開閉">{menuOpen ? <X /> : <Menu />}</button></header>
    <section className="intro" id="top"><div className="eyebrow"><span /> PORTFOLIO 2026</div><div className="intro-grid"><h1>DESIGN THAT<br /><em>MOVES</em> PEOPLE.</h1><div className="intro-note"><p>業種ごとの目的と顧客心理から逆算し、ワイヤーフレーム、UIデザイン、SEO、実装まで一貫して設計。</p><a href="#works">作品を見る <ArrowDownRight /></a></div></div><div className="stats"><div><strong>05</strong><span>INDUSTRIES</span></div><div><strong>15</strong><span>DELIVERABLES</span></div><div><strong>05</strong><span>TECHNOLOGIES</span></div></div><div className="ticker" aria-hidden="true"><span>STRATEGY — WIREFRAME — VISUAL DESIGN — SEO — FRONTEND — STRATEGY — WIREFRAME — VISUAL DESIGN — SEO — FRONTEND —</span></div></section>
    <section className="works" id="works"><div className="section-title"><span>01 / SELECTED WORKS</span><h2>5つの業界、<br />5つの勝ち筋。</h2></div><div className="industry-list">{industries.map((item) => <button key={item.id} className={`industry-row ${activeId === item.id ? "active" : ""}`} onClick={() => selectIndustry(item.id)}><span>{item.number}</span><strong>{item.name}</strong><em>{item.english}</em><p>{item.concept}</p><ArrowDownRight /></button>)}</div></section>
    <section className={`case-study theme-${active.id}`} id="case-study" style={theme}><div className="case-header"><div><span>CASE {active.number}</span><h2>{active.brand}</h2></div><div className="case-meta"><p><b>TARGET</b>{active.audience}</p><p><b>GOAL</b>{active.goal}</p></div></div><div className="design-system"><div className="visual-thesis"><Palette /><span>VISUAL THESIS</span><h3>{active.concept}</h3><p>{active.mood}</p></div><div className="token-panel"><div><span>COLOR</span><i style={{ background: active.primary }} /><i style={{ background: active.secondary }} /><i style={{ background: active.surface }} /></div><div><span>TYPE</span><strong>{active.font}</strong></div><div><span>KEYWORDS</span><strong>{active.tags.join(" / ")}</strong></div></div></div>
      <div className="deliverables"><article><div className="deliverable-head"><span>01</span><div><small>HOMEPAGE</small><h3>HPデザイン</h3></div><p>ブランド理解から予約・購入へ自然につなぐ、回遊型の公式サイト。</p></div><WebsitePreview item={active} /></article><article><div className="deliverable-head"><span>02</span><div><small>LANDING PAGE</small><h3>LPデザイン</h3></div><p>悩み・価値・証拠・オファーを一本の物語にした、成果重視の縦長設計。</p></div><div className="lp-stage"><LandingPreview item={active} /><div className="lp-notes"><span>CONVERSION FLOW</span>{active.lpSections.map((s, i) => <p key={s}><b>0{i + 1}</b>{s}</p>)}</div></div></article><article><div className="deliverable-head"><span>03</span><div><small>DISPLAY AD</small><h3>バナーデザイン</h3></div><p>一瞬で内容が伝わる視線設計。SNS広告にも展開できる比率を想定。</p></div><BannerPreview item={active} /></article></div>
    </section>
    <section className="process" id="process"><div className="section-title light"><span>02 / DESIGN PROCESS</span><h2>意図を、<br />形にする。</h2></div><div className="process-intro"><p>見た目からではなく、誰に・何を・どの順番で伝えるかを定義してから制作。HP・LP・バナーでメッセージを一貫させます。</p></div><div className="wire-grid"><Wireframe title="HP / 回遊型" blocks={active.hpSections} /><Wireframe title="LP / 獲得型" blocks={active.lpSections} /><Wireframe title="BANNER / 認知型" blocks={["キャッチ", "ベネフィット", "CTA"]} /></div><div className="steps">{[["01", "DISCOVER", "競合・顧客・検索意図を整理"], ["02", "STRUCTURE", "情報設計とワイヤーフレーム"], ["03", "DESIGN", "業界に合う独自の視覚言語"], ["04", "BUILD", "レスポンシブ・アクセシブル実装"]].map(([n, en, ja]) => <div key={n}><b>{n}</b><span>{en}</span><p>{ja}</p></div>)}</div></section>
    <section className="seo-section" id="seo"><div className="section-title"><span>03 / SEO & QUALITY</span><h2>検索にも、人にも、<br />正しく伝わる。</h2></div><div className="seo-grid"><div className="search-card"><div><Search size={18} /><span>Google</span></div><small>{active.brand.toLowerCase().replaceAll(" ", "-")}.jp</small><h3>{active.name}なら{active.brand}｜{active.concept}</h3><p>{active.subcopy} 料金・サービス内容・アクセス情報をご案内します。</p></div><div className="quality-list">{["業種＋地域＋目的を含むtitle設計", "見出し階層と検索意図の一致", "LocalBusiness / Product構造化データ", "画像alt・WebP・遅延読み込み", "Core Web Vitalsを意識した軽量実装", "CTAの計測イベント設計"].map((item) => <p key={item}><Check />{item}</p>)}</div></div></section>
    <section className="code-section" id="code"><div className="section-title light"><span>04 / FRONTEND</span><h2>デザインを、<br />動く品質へ。</h2></div><div className="tech-grid">{techs.map(([name, description]) => <button key={name} onClick={() => setCodeTab(name as keyof typeof codeSamples)} className={codeTab === name ? "active" : ""}><Code2 /><b>{name}</b><span>{description}</span></button>)}</div><div className="code-window"><div className="code-top"><span>{codeTab}</span><div><i /><i /><i /></div></div><pre><code>{codeSamples[codeTab]}</code></pre></div><div className="code-note"><MousePointer2 /><p>このポートフォリオ自体を <strong>TypeScript + React + Tailwind CSS</strong> で実装。業種データを切り替えるだけで、配色・コピー・構成・制作物が連動します。</p></div></section>
    <section className="contact-section" id="contact">
      <div className="contact-copy"><span>05 / CONTACT</span><h2>LET&apos;S MAKE<br /><em>IT WORK.</em></h2><p>Webサイト・LP・バナー制作、フロントエンド実装についてご相談ください。内容を確認し、通常2営業日以内にご連絡します。</p><div className="contact-points"><p><Check /> 相談・概算見積もり無料</p><p><Check /> オンライン打ち合わせ対応</p><p><Check /> デザインから実装まで一貫対応</p></div></div>
      <div className="form-shell">
        {submitted ? <div className="form-success" role="status"><CheckCircle2 /><small>MESSAGE RECEIVED</small><h3>お問い合わせを<br />受け付けました。</h3><p>内容を確認し、通常2営業日以内にご連絡します。送信内容は非公開の運用画面で安全に管理されます。</p><Button type="button" onClick={() => setSubmitted(false)}>別の相談を送る</Button></div> :
        <form onSubmit={handleInquiry}>
          <div className="form-heading"><span>PROJECT INQUIRY</span><p><b>*</b> 必須項目</p></div>
          <div className="field-row"><label>お名前 <b>*</b><Input name="name" autoComplete="name" required placeholder="例：山田 太郎" /></label><label>会社名・屋号<Input name="company" autoComplete="organization" placeholder="例：株式会社○○" /></label></div>
          <label>メールアドレス <b>*</b><Input name="email" type="email" autoComplete="email" required placeholder="example@email.com" /></label>
          <div className="field-row"><label>ご相談内容 <b>*</b><NativeSelect name="projectType" required defaultValue=""><NativeSelectOption value="" disabled>選択してください</NativeSelectOption><NativeSelectOption>ホームページ制作</NativeSelectOption><NativeSelectOption>LP制作</NativeSelectOption><NativeSelectOption>バナー制作</NativeSelectOption><NativeSelectOption>フロントエンド実装</NativeSelectOption><NativeSelectOption>その他</NativeSelectOption></NativeSelect></label><label>ご予算<NativeSelect name="budget" defaultValue=""><NativeSelectOption value="">未定・相談したい</NativeSelectOption><NativeSelectOption>5万円未満</NativeSelectOption><NativeSelectOption>5〜15万円</NativeSelectOption><NativeSelectOption>15〜30万円</NativeSelectOption><NativeSelectOption>30万円以上</NativeSelectOption></NativeSelect></label></div>
          <label>希望納期<NativeSelect name="schedule" defaultValue=""><NativeSelectOption value="">未定・相談したい</NativeSelectOption><NativeSelectOption>1か月以内</NativeSelectOption><NativeSelectOption>2〜3か月以内</NativeSelectOption><NativeSelectOption>3か月以上先</NativeSelectOption></NativeSelect></label>
          <label>ご相談内容の詳細 <b>*</b><Textarea name="message" required minLength={20} rows={7} placeholder="目的、必要なページ、参考サイト、現在のお困りごとなどをご記入ください。" /></label><label className="honeypot" aria-hidden="true">Webサイト<Input name="website" tabIndex={-1} autoComplete="off" /></label>
          <label className="privacy-check"><input type="checkbox" required /><span>入力内容を案件相談の確認目的で利用することに同意します。 <b>*</b></span></label>
          {formError && <p className="form-error" role="alert">{formError}</p>}<Button className="submit-button" type="submit" disabled={submitting}>{submitting ? "送信しています…" : "案件相談を送信する"} <Send /></Button><p className="form-caption">送信内容は案件対応以外の目的には利用しません。</p>
        </form>}
      </div>
    </section>
    <footer><div><Sparkles /><span>AVAILABLE FOR WEB DESIGN & FRONTEND</span></div><h2>GOOD DESIGN<br />STARTS WITH<br /><em>A CLEAR GOAL.</em></h2><a href="#top">BACK TO TOP <ExternalLink /></a><p>© 2026 KENTA CREATIVE PORTFOLIO　<Link className="ops-link" href="/services">料金・制作条件</Link>　<Link className="ops-link" href="/privacy">プライバシー</Link>　<Link className="ops-link" href="/ops">運用ログイン</Link></p></footer>
  </main>;
}
