"use client";

import { useMemo, useState, type CSSProperties, type FormEvent } from "react";
import Image from "next/image";
import { ReliableLink } from "@/components/atoms/reliable-link";
import { PortfolioSectionHeading as SectionHeading } from "@/components/molecules/portfolio-section-heading";
import { ArrowDownRight, Check, CheckCircle2, ChevronRight, Code2, ExternalLink, GitPullRequest, LayoutTemplate, Menu, MousePointer2, Palette, Search, Send, ShieldCheck, Sparkles, X, Zap } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { INQUIRY_MESSAGE_MIN_LENGTH } from "@/lib/inquiry-validation";

type Industry = {
  id: string; number: string; name: string; english: string; brand: string; concept: string;
  audience: string; goal: string; primary: string; secondary: string; ink: string; surface: string;
  image?: string; hero: string; subcopy: string; cta: string; accentCopy: string;
  hpSections: string[]; lpSections: string[]; bannerCopy: string; tags: string[]; font: string; mood: string;
};

const industries: Industry[] = [
  { id: "beauty", number: "01", name: "美容", english: "BEAUTY", brand: "LUMIÈRE SKIN", concept: "静けさの中に宿る、透明感。", audience: "30〜40代／自分の肌と丁寧に向き合いたい人", goal: "初回カウンセリング予約", primary: "#D8C29D", secondary: "#8E7256", ink: "#F8F4EC", surface: "#171713", image: "/beauty-hero.webp", hero: "肌は、もっと静かに美しくなる。", subcopy: "一人ひとりの肌履歴を読み解く、完全予約制スキンケアサロン。", cta: "肌診断を予約する", accentCopy: "FIRST TRIAL ¥6,600", hpSections: ["CONCEPT", "TREATMENT", "VOICE", "SALON", "RESERVE"], lpSections: ["悩みへの共感", "3つの原因", "施術メソッド", "症例・口コミ", "限定オファー"], bannerCopy: "初回限定｜肌質改善トリートメント 40% OFF", tags: ["余白", "高級感", "信頼性"], font: "Noto Serif JP × Inter", mood: "Editorial / Quiet luxury" },
  { id: "food", number: "02", name: "飲食", english: "DINING", brand: "季ノ皿 KINOSARA", concept: "旬を一皿に、夜を記憶に。", audience: "食に関心の高い30〜50代／記念日・会食利用", goal: "ディナーコース予約", primary: "#B6403A", secondary: "#E2B66A", ink: "#FFF8E8", surface: "#25130F", image: "/food-hero.webp", hero: "今夜、旬に会いに行く。", subcopy: "産地の景色まで味わう、季節の日本料理とナチュラルワイン。", cta: "席を予約する", accentCopy: "AUTUMN COURSE 7皿 ¥8,800", hpSections: ["旬の献立", "料理人", "空間", "お知らせ", "ご予約"], lpSections: ["季節の物語", "コース紹介", "生産者", "お客様の声", "空席案内"], bannerCopy: "秋の実りを味わう｜限定ペアリングコース", tags: ["食欲喚起", "季節感", "予約導線"], font: "Shippori Mincho × Manrope", mood: "Warm / Gastronomy" },
  { id: "fashion", number: "03", name: "アパレル", english: "FASHION", brand: "ÉLAN STUDIO", concept: "輪郭を着る。意思を纏う。", audience: "20〜30代／モードとストリートを横断する層", goal: "新作コレクション購入", primary: "#D9FF43", secondary: "#214BFF", ink: "#0B0B0B", surface: "#F6F5EF", image: "/fashion-hero.webp", hero: "WEAR YOUR POINT.", subcopy: "曖昧な毎日に、鮮明なシルエットを。SPRING / SUMMER 2026", cta: "COLLECTIONを見る", accentCopy: "DROP 02 — NOW ONLINE", hpSections: ["NEW DROP", "COLLECTION", "LOOKBOOK", "JOURNAL", "STORE"], lpSections: ["キービジュアル", "NEW ITEMS", "スタイリング", "サイズガイド", "購入CTA"], bannerCopy: "NEW DROP 02｜送料無料 9.20まで", tags: ["大胆な文字", "非対称", "スピード感"], font: "Archivo Black × Noto Sans JP", mood: "Neo editorial / Street" },
  { id: "energy", number: "04", name: "電気会社", english: "ENERGY", brand: "HIKARI ENERGY", concept: "電気を、選べる未来へ。", audience: "ファミリー世帯／電気代と環境負荷を見直したい人", goal: "料金シミュレーション完了", primary: "#62E6C7", secondary: "#3D6CFF", ink: "#F4FAFF", surface: "#071B35", hero: "使うほど、未来が明るくなる電気。", subcopy: "再生可能エネルギー比率70%。暮らしに合わせて選べるシンプルな料金プラン。", cta: "電気代を30秒で診断", accentCopy: "平均 年間12,400円 おトク", hpSections: ["料金プラン", "再エネ", "導入事例", "サポート", "会社情報"], lpSections: ["料金課題", "節約シミュレーション", "選ばれる理由", "切替手順", "申込み"], bannerCopy: "切替0円｜基本料金3か月無料キャンペーン", tags: ["安心", "明瞭", "未来感"], font: "Zen Kaku Gothic New × Inter", mood: "Clean tech / Trust" },
  { id: "campaign", number: "05", name: "キャンペーン", english: "CAMPAIGN", brand: "TOKYO CREATIVE WEEK", concept: "東京を、アイデアの会場に。", audience: "クリエイター・学生・新しい表現に出会いたい人", goal: "無料参加登録", primary: "#E45B3B", secondary: "#4E51A4", ink: "#F3F0E8", surface: "#12151C", hero: "THE CITY IS THE VENUE.", subcopy: "展示、トーク、ワークショップ。東京の47会場を歩いて巡るクリエイティブフェス。", cta: "無料パスを手に入れる", accentCopy: "10.12 SUN — 10.18 SAT", hpSections: ["PROGRAM", "SPEAKERS", "VENUES", "NEWS", "TICKETS"], lpSections: ["開催宣言", "注目プログラム", "登壇者", "会場MAP", "参加登録"], bannerCopy: "東京を、アイデアの会場に。", tags: ["都市型", "編集的", "回遊導線"], font: "Space Grotesk × Noto Sans JP", mood: "Editorial festival / Wayfinding" },
];

const techs = [["HTML", "セマンティックな見出し構造と構造化データ"], ["CSS", "業種別トークン・レスポンシブ・アニメーション"], ["JavaScript", "タブ切替・CTA計測・メニュー制御"], ["Tailwind CSS", "素早く再利用できるUI設計"], ["TypeScript", "デザインデータとUI状態を型安全に管理"]];
const codeSamples = {
  HTML: `<main>\n  <article itemscope itemtype="https://schema.org/LocalBusiness">\n    <h1>ブランドの約束を一文で伝える</h1>\n    <a href="#reserve">予約する</a>\n  </article>\n</main>`,
  CSS: `:root {\n  --brand: #d9ff43;\n  --space-section: clamp(5rem, 10vw, 10rem);\n}\n.hero {\n  display: grid;\n  grid-template-columns: 1.1fr .9fr;\n}`,
  JavaScript: `document.querySelectorAll('[data-cta]').forEach((button) => {\n  button.addEventListener('click', () => {\n    window.dataLayer?.push({ event: 'cta_click' });\n  });\n});`,
  "Tailwind CSS": `<section className="grid min-h-[80vh] items-end\n  bg-zinc-950 px-6 py-16 text-white md:grid-cols-2 md:px-12">\n  <h1 className="text-6xl font-black tracking-[-.06em] md:text-8xl">\n    WEAR YOUR POINT.\n  </h1>\n</section>`,
  TypeScript: `type Industry = {\n  id: string;\n  goal: '予約' | '購入' | '申込';\n  palette: readonly [string, string];\n};\n\nconst trackCTA = (item: Industry) =>\n  analytics.track('conversion', { industry: item.id });`,
};

function MiniNav({ item }: { item: Industry }) { return <div className="mini-nav"><strong>{item.brand}</strong><span>{item.hpSections.slice(0, 3).join("　")}</span><Menu size={16} /></div>; }
function HeroVisual({ item, compact = false }: { item: Industry; compact?: boolean }) {
  if (item.image) return <div className={`hero-image ${compact ? "compact" : ""}`}><Image src={item.image} alt={`${item.name}業界の${item.brand}キービジュアル`} width={1536} height={1024} sizes="(max-width: 700px) 100vw, 45vw" unoptimized /></div>;
  if (item.id === "campaign") return <div className={`generated-visual campaign ${compact ? "compact" : ""}`} aria-label="東京の街を会場に見立てたクリエイティブフェスのキービジュアル"><span className="visual-grid" /><span className="visual-orbit" /><span className="campaign-kicker">CREATIVE FESTIVAL / TOKYO</span><strong className="campaign-display">47<br />VENUES</strong><span className="campaign-date">OCT 12—18 / 2026</span><span className="campaign-index">120 CREATORS</span></div>;
  return <div className={`generated-visual ${item.id} ${compact ? "compact" : ""}`} aria-label={`${item.name}の抽象ビジュアル`}><span className="visual-orbit" /><span className="visual-grid" /><Zap className="visual-icon" aria-hidden="true" /></div>;
}
function WebsitePreview({ item }: { item: Industry }) { return <div className="browser-frame preview-hp"><div className="browser-top"><i /><i /><i /><span>{item.brand.toLowerCase().replaceAll(" ", "-")}.jp</span></div><MiniNav item={item} /><div className="mini-hero"><div className="mini-copy"><small>{item.accentCopy}</small><h4>{item.hero}</h4><p>{item.subcopy}</p><a href="#contact">{item.cta} <ArrowDownRight size={13} /></a></div><HeroVisual item={item} compact /></div><div className="mini-proof">{item.hpSections.slice(1, 4).map((section, index) => <div key={section}><b>0{index + 1}</b><span>{section}</span><em /></div>)}</div></div>; }
function LandingPreview({ item }: { item: Industry }) { return <div className="phone-frame preview-lp"><div className="phone-status"><span>9:41</span><i /></div><div className="lp-head"><b>{item.brand}</b><Menu size={14} /></div><HeroVisual item={item} compact /><div className="lp-copy"><small>{item.accentCopy}</small><h4>{item.hero}</h4><a href="#contact">{item.cta}</a></div><div className="lp-flow">{item.lpSections.slice(0, 4).map((section, index) => <div key={section}><i>0{index + 1}</i><span>{section}</span></div>)}</div></div>; }
function BannerPreview({ item }: { item: Industry }) { return <div className={`banner-preview ${item.id}`}><div className="banner-copy"><small>{item.brand}</small><h4>{item.bannerCopy}</h4><span>{item.cta} <ChevronRight size={13} /></span></div><HeroVisual item={item} compact /><b className="banner-mark">{item.number}</b></div>; }
function Wireframe({ title, blocks }: { title: string; blocks: string[] }) { return <div className="wire-card"><div className="wire-head"><span>{title}</span><LayoutTemplate size={16} /></div><div className="wire-body">{blocks.map((block, index) => <div className={`wire-block wire-${index}`} key={block}><span>{block}</span><i /><i /></div>)}</div></div>; }

export default function Home() {
  const [activeId, setActiveId] = useState("beauty"); const [menuOpen, setMenuOpen] = useState(false); const [codeTab, setCodeTab] = useState<keyof typeof codeSamples>("HTML"); const [submitted, setSubmitted] = useState(false); const [submitting, setSubmitting] = useState(false); const [formError, setFormError] = useState(""); const [messageLength, setMessageLength] = useState(0); const [startedAt] = useState(() => Date.now());
  const active = useMemo(() => industries.find((item) => item.id === activeId) ?? industries[0], [activeId]);
  const theme = { "--case-primary": active.primary, "--case-secondary": active.secondary, "--case-ink": active.ink, "--case-surface": active.surface } as CSSProperties;
  const selectIndustry = (id: string) => { setActiveId(id); document.getElementById("case-study")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const handleInquiry = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setFormError("");
    const form = event.currentTarget; const formValues = Object.fromEntries(new FormData(form).entries()) as Record<string, FormDataEntryValue>; const data = { ...formValues, startedAt };
    const message = String(formValues["message"] ?? "").trim();
    if (message.length < INQUIRY_MESSAGE_MIN_LENGTH) { setFormError(`ご相談内容の詳細を${INQUIRY_MESSAGE_MIN_LENGTH}文字以上で入力してください。`); (form.elements.namedItem("message") as HTMLTextAreaElement | null)?.focus(); return; }
    setSubmitting(true);
    void fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:"contact_start",path:location.pathname})});
    try { const response = await fetch("/api/inquiries", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(data) }); const result = await response.json() as { error?:string }; if (!response.ok) throw new Error(result.error || "送信できませんでした"); void fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:"contact_submit",path:location.pathname})}); setSubmitted(true); setMessageLength(0); form.reset(); document.getElementById("contact")?.scrollIntoView({ behavior:"smooth", block:"center" }); }
    catch (error) { void fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:"contact_error",path:location.pathname})}); setFormError(`${error instanceof Error ? error.message : "送信できませんでした"} 入力内容は保持されています。時間をおいて再度お試しください。`); }
    finally { setSubmitting(false); }
  };
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="ページ上部へ"><span>K</span> KENTY CREATIVE</a><nav className={menuOpen ? "nav-open" : ""} aria-label="メインナビゲーション"><a href="#audiences" onClick={() => setMenuOpen(false)}>FOR YOU</a><ReliableLink href="/works" onClick={() => setMenuOpen(false)}>WORKS</ReliableLink><a href="#interactive" onClick={() => setMenuOpen(false)}>DEMOS</a><ReliableLink href="/services" onClick={() => setMenuOpen(false)}>SERVICES</ReliableLink><a className="nav-contact" href="#contact" onClick={() => setMenuOpen(false)}>無料で案件相談する</a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="メニューを開閉">{menuOpen ? <X /> : <Menu />}</button></header>
    <section className="intro" id="top"><div className="eyebrow"><span /> DESIGN. BUILD. IMPROVE.</div><div className="intro-grid"><h1 className="hero-ja">HP・LP・ECを、<br/>設計からReact実装まで。</h1><div className="intro-note"><p>問い合わせ・予約・購入につなげるWeb制作。目的整理からUI設計、React・TypeScript実装、テスト、公開後の改善まで一貫して支援します。</p><div className="intro-actions"><a className="intro-primary" href="#contact">無料で案件相談する <ArrowDownRight /></a><ReliableLink href="/works">制作事例を見る</ReliableLink><ReliableLink href="/services">料金・制作条件を見る</ReliableLink></div></div></div><div className="stats"><div><strong>05+</strong><span>WEB業界経験 / 5年以上</span></div><div><strong>03</strong><span>REACT・TYPESCRIPT実務 / 3年</span></div><div><strong>1年7か月</strong><span>制作会社でのHP・LP制作</span></div></div><div className="ticker" aria-hidden="true"><span>EC DEVELOPMENT — WEB DESIGN — LANDING PAGE — TESTING — OPERATION — EC DEVELOPMENT — WEB DESIGN — LANDING PAGE — TESTING — OPERATION —</span></div></section>
    <section className="audience-section" id="audiences"><div><small>FOR STORES & BUSINESS OWNERS</small><h2>店舗・事業者の方へ</h2><p>HP、LP、予約フォームを、集客と運用の流れまで含めて制作します。</p><div><ReliableLink href="/services/homepage">ホームページ制作</ReliableLink><ReliableLink href="/services/landing-page">LP制作</ReliableLink><ReliableLink href="/services/booking-system">予約フォーム</ReliableLink></div></div><div><small>FOR AGENCIES & PRODUCT TEAMS</small><h2>制作会社・開発チームの方へ</h2><p>React・TypeScript実装、UI改修、テスト、コンポーネント整理を支援します。</p><div><ReliableLink href="/services/frontend">フロントエンド開発</ReliableLink><ReliableLink href="/services/maintenance">保守・改善</ReliableLink></div></div></section>
    <section className="strengths" id="strengths"><SectionHeading number="01" label="WHY KENTY">設計から改善まで、ひとつの視点で。</SectionHeading><p className="strengths-lead">制作会社でのWeb制作と、React・TypeScriptによるEC開発の経験を掛け合わせ、デザインと実装の間を途切れさせません。</p><div className="strength-grid"><article><Code2/><small>FRONTEND</small><h3>React・TypeScript<br/>実務3年</h3><p>ECサイトの画面開発、フォーム、状態管理、コンポーネント設計、結合テストまで対応。</p></article><article><Palette/><small>WEB PRODUCTION</small><h3>HP・LP制作<br/>1年7か月</h3><p>美容・飲食・アパレル・電気会社など、業種に合わせたレスポンシブ制作と運用改修。</p></article><article><GitPullRequest/><small>QUALITY & OPERATION</small><h3>作って終わらない<br/>運用品質</h3><p>Atomic Design、コードレビュー、TypeScriptテスト、公開後の更新を見据えた構成。</p></article></div><div className="strength-proof"><ShieldCheck/><p><b>対応範囲</b> 情報整理・ワイヤー・UIデザイン・フロントエンド実装・テスト・公開後の改善</p><ReliableLink href="/services">プロフィールと制作条件を見る <ChevronRight/></ReliableLink></div></section>
    <section className="works" id="works"><SectionHeading number="02" label="SELECTED WORKS">5つの業界、5つの設計判断。</SectionHeading><div className="industry-list">{industries.map((item) => <button key={item.id} className={`industry-row ${activeId === item.id ? "active" : ""}`} onClick={() => selectIndustry(item.id)}><span>{item.number}</span><strong>{item.name}</strong><em>{item.english}</em><p>{item.concept}</p><ArrowDownRight /></button>)}</div><ReliableLink className="works-index-link" href="/works">課題・判断・テストを含む事例一覧を見る <ArrowDownRight/></ReliableLink></section>
    <section className={`case-study theme-${active.id}`} id="case-study" style={theme}><div className="case-header"><div><span>CASE {active.number}</span><h2>{active.brand}</h2></div><div className="case-meta"><p><b>TARGET</b>{active.audience}</p><p><b>GOAL</b>{active.goal}</p></div></div><div className="design-system"><div className="visual-thesis"><Palette /><span>VISUAL THESIS</span><h3>{active.concept}</h3><p>{active.mood}</p></div><div className="token-panel"><div><span>COLOR</span><i style={{ background: active.primary }} /><i style={{ background: active.secondary }} /><i style={{ background: active.surface }} /></div><div><span>TYPE</span><strong>{active.font}</strong></div><div><span>KEYWORDS</span><strong>{active.tags.join(" / ")}</strong></div></div></div>
      <div className="deliverables"><article><div className="deliverable-head"><div className="deliverable-copy"><small>01 / HOMEPAGE</small><h3>HPデザイン</h3><p>ブランド理解から予約・購入へ自然につなぐ、回遊型の公式サイト。</p></div></div><WebsitePreview item={active} /></article><article><div className="deliverable-head"><div className="deliverable-copy"><small>02 / LANDING PAGE</small><h3>LPデザイン</h3><p>悩み・価値・証拠・オファーを一本の物語にした、成果重視の縦長設計。</p></div></div><div className="lp-stage"><LandingPreview item={active} /><div className="lp-notes"><span>CONVERSION FLOW</span>{active.lpSections.map((s, i) => <p key={s}><b>0{i + 1}</b>{s}</p>)}</div></div></article><article><div className="deliverable-head"><div className="deliverable-copy"><small>03 / DISPLAY AD</small><h3>バナーデザイン</h3><p>一瞬で内容が伝わる視線設計。SNS広告にも展開できる比率を想定。</p></div></div><BannerPreview item={active} /></article></div>
    </section>
    <section className="process" id="process"><SectionHeading number="03" label="DESIGN PROCESS" light>意図を、形にする。</SectionHeading><div className="process-intro"><p>見た目からではなく、誰に・何を・どの順番で伝えるかを定義してから制作。HP・LP・バナーでメッセージを一貫させます。</p></div><div className="wire-grid"><Wireframe title="HP / 回遊型" blocks={active.hpSections} /><Wireframe title="LP / 獲得型" blocks={active.lpSections} /><Wireframe title="BANNER / 認知型" blocks={["キャッチ", "ベネフィット", "CTA"]} /></div><div className="steps">{[["01", "DISCOVER", "競合・顧客・検索意図を整理"], ["02", "STRUCTURE", "情報設計とワイヤーフレーム"], ["03", "DESIGN", "業界に合う独自の視覚言語"], ["04", "BUILD", "レスポンシブ・アクセシブル実装"]].map(([n, en, ja]) => <div key={n}><b>{n}</b><span>{en}</span><p>{ja}</p></div>)}</div></section>
    <section className="seo-section" id="seo"><SectionHeading number="04" label="SEO & QUALITY">検索にも、人にも、正しく伝わる。</SectionHeading><div className="seo-grid"><div className="search-card"><div><Search size={18} /><span>Google</span></div><small>{active.brand.toLowerCase().replaceAll(" ", "-")}.jp</small><h3>{active.name}なら{active.brand}｜{active.concept}</h3><p>{active.subcopy} 料金・サービス内容・アクセス情報をご案内します。</p></div><div className="quality-list">{["TypeScript自動テストを公開前に実行", "型検査・コード検査・本番ビルドを確認", "見出し階層と検索意図の一致", "構造化データ・OGP・サイトマップ", "画像alt・WebP・遅延読み込み", "個人情報を含めない匿名イベント計測"].map((item) => <p key={item}><Check />{item}</p>)}</div></div></section>
    <section className="code-section" id="code"><SectionHeading number="05" label="FRONTEND" light>デザインを、動く品質へ。</SectionHeading><div className="tech-grid">{techs.map(([name, description]) => <button key={name} onClick={() => setCodeTab(name as keyof typeof codeSamples)} className={codeTab === name ? "active" : ""}><Code2 /><b>{name}</b><span>{description}</span></button>)}</div><div className="code-window"><div className="code-top"><span>{codeTab}</span><div><i /><i /><i /></div></div><pre><code>{codeSamples[codeTab]}</code></pre></div><div className="code-note"><MousePointer2 /><p>このポートフォリオ自体を <strong>TypeScript + React + Tailwind CSS</strong> で実装。業種データを切り替えるだけで、配色・コピー・構成・制作物が連動します。</p></div></section>
    <section className="interactive-section" id="interactive"><SectionHeading number="06" label="INTERACTIVE CASES">触れてわかる、実装事例。</SectionHeading><p className="interactive-lead">完成画面だけでなく、アプリ操作、購入、予約、管理まで実際に体験できる自主制作です。個人情報や決済情報は外部送信されません。</p><div className="interactive-grid"><article className="interactive-card mobile-app"><div className="mobile-app-visual" aria-hidden="true"><span>9:41</span><strong>今日の習慣</strong><i/><i/><i/><b>2 / 4 完了</b></div><div className="interactive-copy"><small>CASE 06 / REACT NATIVE</small><h3>習慣管理<br/>モバイルアプリ</h3><p>React Native・Expo・TypeScriptを想定。習慣記録、進捗、設定を操作できます。</p><ReliableLink href="/react-native-app">アプリ事例を体験 <ArrowDownRight/></ReliableLink></div></article><article className="interactive-card vtuber"><div className="interactive-visual"><Image src="/vtuber-luna-hero.webp" alt="架空VTuber公式ECサイトのキービジュアル" width={1916} height={821} sizes="(max-width: 760px) 100vw, 50vw"/></div><div className="interactive-copy"><small>CASE 07 / CREATOR COMMERCE</small><h3>個人VTuber<br/>公式ECサイト</h3><p>ファンの熱量を購入へつなぐ世界観設計。商品絞り込み、カート追加、数量変更まで体験できます。</p><ReliableLink href="/vtuber-shop">ECサイトを体験 <ArrowDownRight/></ReliableLink></div></article><article className="interactive-card izakaya"><div className="interactive-visual"><Image src="/food-hero.webp" alt="居酒屋HPと予約管理デモ" width={1536} height={1024} sizes="(max-width: 760px) 100vw, 50vw"/></div><div className="interactive-copy"><small>CASE 08 / LOCAL BUSINESS</small><h3>居酒屋HP・予約<br/>管理者体験</h3><p>店舗紹介から予約登録、管理画面での確認・ステータス変更まで、一連の運用を体験できます。</p><div className="interactive-links"><ReliableLink href="/izakaya">店舗HPを見る <ArrowDownRight/></ReliableLink><ReliableLink href="/izakaya/admin">管理画面を体験</ReliableLink></div></div></article></div></section>
    <section className="offer-section" id="offer"><SectionHeading number="07" label="START A PROJECT">頼みたい内容から、選べます。</SectionHeading><div className="offer-grid"><article><small>01 / FRONTEND</small><h3>React・TypeScript<br/>実装／改修</h3><p>画面追加、既存UIの修正、レスポンシブ対応、コンポーネント整理、テスト実装。</p><div><span>目安</span><strong>¥50,000〜</strong></div></article><article><small>02 / LANDING PAGE</small><h3>LPデザイン<br/>＋実装</h3><p>目的・ターゲット整理から構成、UIデザイン、コーディング、基本SEOまで。</p><div><span>目安</span><strong>¥180,000〜</strong></div></article><article><small>03 / MAINTENANCE</small><h3>公開後の<br/>保守・改善</h3><p>更新対応、表示崩れ修正、導線・SEO改善。スポット対応も相談できます。</p><div><span>月額</span><strong>¥20,000〜</strong></div></article></div><div className="offer-actions"><p>Webサイト制作、バナー、予約フォーム、業務委託のご相談にも対応します。</p><div><ReliableLink href="/services">料金・制作条件を見る <ChevronRight/></ReliableLink><a href="#contact">無料で案件相談する <ArrowDownRight/></a></div></div></section>
    <section className="contact-section" id="contact">
      <div className="contact-copy"><SectionHeading number="08" label="CONTACT" className="contact-title">無料で案件相談する。</SectionHeading><p>未確定の内容があっても大丈夫です。入力時間の目安は2〜3分。通常2営業日以内にご連絡します。</p><div className="contact-points"><p><Check /> 相談のみでも可・無理な営業なし</p><p><Check /> 秘密保持契約も相談可能</p><p><Check /> オンライン打ち合わせ対応</p></div></div>
      <div className="form-shell">
        {submitted ? <div className="form-success" role="status"><CheckCircle2 /><small>MESSAGE RECEIVED</small><h3>お問い合わせを<br />受け付けました。</h3><p>内容を確認し、通常2営業日以内にご連絡します。送信内容は非公開の運用画面で安全に管理されます。</p><Button type="button" onClick={() => setSubmitted(false)}>別の相談を送る</Button></div> :
        <form onSubmit={handleInquiry}>
          <div className="form-heading"><span>PROJECT INQUIRY</span><p><b>*</b> 必須項目</p></div>
          <div className="field-row"><label>お名前 <b>*</b><Input name="name" autoComplete="name" required placeholder="例：山田 太郎" /></label><label>会社名・屋号<Input name="company" autoComplete="organization" placeholder="例：株式会社○○" /></label></div>
          <label>メールアドレス <b>*</b><Input name="email" type="email" autoComplete="email" required placeholder="example@email.com" /></label>
          <div className="field-row"><label>依頼区分 <b>*</b><NativeSelect name="clientType" required defaultValue=""><NativeSelectOption value="" disabled>選択してください</NativeSelectOption><NativeSelectOption>店舗・個人事業</NativeSelectOption><NativeSelectOption>企業・団体</NativeSelectOption><NativeSelectOption>制作会社・開発会社</NativeSelectOption><NativeSelectOption>その他</NativeSelectOption></NativeSelect></label><label>ご相談内容 <b>*</b><NativeSelect name="projectType" required defaultValue=""><NativeSelectOption value="" disabled>選択してください</NativeSelectOption><NativeSelectOption>ホームページ制作</NativeSelectOption><NativeSelectOption>LP制作</NativeSelectOption><NativeSelectOption>バナー制作</NativeSelectOption><NativeSelectOption>予約フォーム</NativeSelectOption><NativeSelectOption>フロントエンド実装</NativeSelectOption><NativeSelectOption>業務委託・開発チーム参画</NativeSelectOption><NativeSelectOption>保守・改善</NativeSelectOption><NativeSelectOption>その他</NativeSelectOption></NativeSelect></label></div>
          <div className="field-row"><label>ご予算<NativeSelect name="budget" defaultValue=""><NativeSelectOption value="">未定・相談したい</NativeSelectOption><NativeSelectOption>5万円未満</NativeSelectOption><NativeSelectOption>5〜15万円</NativeSelectOption><NativeSelectOption>15〜30万円</NativeSelectOption><NativeSelectOption>30万円以上</NativeSelectOption></NativeSelect></label><label>希望納期<NativeSelect name="schedule" defaultValue=""><NativeSelectOption value="">未定・相談したい</NativeSelectOption><NativeSelectOption>1か月以内</NativeSelectOption><NativeSelectOption>2〜3か月以内</NativeSelectOption><NativeSelectOption>3か月以上先</NativeSelectOption></NativeSelect></label></div>
          <label>参考サイト・資料のURL<Input name="referenceUrl" type="url" inputMode="url" placeholder="https://example.com（任意）" /></label>
          <label>ご相談内容の詳細 <b>*</b><Textarea name="message" required minLength={INQUIRY_MESSAGE_MIN_LENGTH} rows={7} aria-describedby="message-count" onChange={(event) => { setMessageLength(event.currentTarget.value.trim().length); if (formError) setFormError(""); }} placeholder="目的、必要なページ、参考サイト、現在のお困りごとなどをご記入ください。" /><span className="field-count" id="message-count">{messageLength}文字（最低{INQUIRY_MESSAGE_MIN_LENGTH}文字）</span></label><label className="honeypot" aria-hidden="true">Webサイト<Input name="website" tabIndex={-1} autoComplete="off" /></label>
          <label className="privacy-check"><input type="checkbox" required /><span>入力内容を案件相談の確認目的で利用することに同意します。 <b>*</b></span></label>
          {formError && <p className="form-error" role="alert">{formError}</p>}<Button className="submit-button" type="submit" disabled={submitting} aria-busy={submitting}>{submitting ? "送信しています…" : "無料で案件相談する"} <Send /></Button><p className="form-caption">送信内容は案件対応以外の目的には利用しません。</p>
        </form>}
      </div>
    </section>
    <footer><div><Sparkles /><span>AVAILABLE FOR WEB DESIGN & FRONTEND</span></div><h2>GOOD DESIGN<br />STARTS WITH<br /><em>A CLEAR GOAL.</em></h2><a href="#top">BACK TO TOP <ExternalLink /></a><p>© 2026 KENTY CREATIVE PORTFOLIO　<ReliableLink className="ops-link" href="/services">料金・制作条件</ReliableLink>　<ReliableLink className="ops-link" href="/privacy">プライバシー</ReliableLink>　<ReliableLink className="ops-link" href="/ops">運用ログイン</ReliableLink></p></footer>
  </main>;
}
